WEAPON_TYPE_NAMES = {
    'Auto rifle' : 'Auto Rifle',
    'autogun' : 'Auto Rifle', 
    'Melee-sword/blade' : 'Melee',
    'near_sword' : 'Melee',
    'Melee-electric saw' : 'Melee',
    'near_saw' : 'Melee',
    'pistol_fast' : 'Pistol',
    'Hand-cannon' : 'Pistol',
    'pistol_heavy' : 'Pistol',
    'Deploy-ancient weapon' : 'Deploy',
    'place_ancient' : 'Deploy',
    'Deploy-batter' : 'Deploy',
    'place_battery' : 'Deploy',
    'Deploy-dolly' : 'Dolly',
    'place_doll' : 'Dolly',
    'Deploy-trap dolly' : 'Deploy',
    'place_induce' : 'Deploy',
    'Deploy mine' : 'Deploy',
    'place_mine' : 'Deploy',
    'Deploy-special' : 'Deploy',
    'place_special' : 'Deploy',
    'Rocket launcher' : 'RPG',
    'rpg' : 'RPG',
    'Spread shotgun' : 'Shotgun',
    'shotgun_multi' : 'Shotgun',
    'Single shotgun' : 'Shotgun',
    'shotgun_single' : 'Shotgun',
    'Sniper rifle' : 'Sniper Rifle',
    'sniper' : 'Sniper Rifle',
    'special' : 'Special',
    'special_bow' : 'Bow',
    'spray' : 'Spray',
    'Activate' : 'Spray',
    'spray_active' : 'Spray',
    'Enchant' : 'Spray',
    'spray_enchanting' : 'Spray',
    'Switch' : 'Spray',
    'spray_switch' : 'Spray',
    'Thrown weapon' : 'Throw',
    'throw' : 'Throw',
    0 : None
}

DAMAGE_TYPE_NAMES = {
    '1' : 'Physical',
    '2' : 'Fire',
    '3' : 'Ice',
    '4' : 'Energy',
    '5' : 'Light',
    '6' : 'Poison',
    'physic' : 'Physical',
    'pure' : 'Physical',
    'fire' : 'Fire',
    'snow' : 'Ice',
    'ice' : 'Ice',
    'power' : 'Energy',
    'light' : 'Light',
    'poison' : 'Poison',
    'none' : None,
    'null' : None,
    ';' : None,
}

PROPERTY_NAMES = {
    '负重' : 'Carry Load',
    '重量' : 'Carry Load',
    '最大等级' : 'Max Lvl',
    'Max LV' : 'Max Lvl',
    '类型' : 'Type',
    'タイプ' : 'Type',
    '满级攻击力' : 'Max Lvl Damage',
    '攻撃力' : 'Max Lvl Damage',
    'MaxLv Attack' : 'Max Lvl Damage',
    'MaxLv Atk' : 'Max Lvl Damage',
    '满级载弹' : 'Max Lvl Ammo',
    '弾薬上限' : 'Max Lvl Ammo',
    'MaxLv Ammo' : 'Max Lvl Ammo',
    '满级攻速' : 'Max Lvl ASPD',
    '攻速' : 'Max Lvl ASPD',
    'MaxLv ASPD' : 'Max Lvl ASPD',
    '暴击率' : 'Crit Rate',
    '会心率' : 'Crit Rate',
    '弹道数' : 'Warheads Num',
    'Shoot Line Num' : 'Warheads Num',
    '满级存在时间' : 'Duration',
    '継続時間' : 'Duration',
    '存在上限' : 'Deploy Upper Limit',
    '設置上限' : 'Deploy Upper Limit',
    '满级生命' : 'Max Lvl HP',
    'HP' : 'Max Lvl HP',
    'MaxLv HP' : 'Max Lvl HP'
}